#!/bin/bash

#List here all the f90 files to compile, separated by spaces
#THERE MUST NOT be spaces around '=' in bash
myprogramfiles="kinds.f90 command_line.f90 RK4_thin_film.f90"

#Name of compiled file
outfile="exec_RK4"

# Name of compiler
fc=gfortran

#Actual compile line. Other flags etc can be added
$fc -g $myprogramfiles -o $outfile #-O3
